---
apiVersion: v1
kind: Namespace
metadata:
  name: eirini

# Deployment
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "eirini"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "eirini"
  template:
    metadata:
      labels:
        name: "eirini"
    spec:
      dnsPolicy: "ClusterFirst"
      serviceAccountName: "opi"
      volumes:
        - name: config-volume
          configMap:
            name: "eirini"
            items:
            - key: opi.yaml
              path: opi.yml
        - name: registry-cert
          secret:
            secretName: private-registry-cert
      containers:
      - name: opi
        image: eirini/opi:no-secure
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /workspace/jobs/opi/config
        ports:
          - containerPort: 8085
      - name: registry
        image: eirini/registry:no-secure
        imagePullPolicy: Always
        restartPolicy: OnFailure
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: registry-cert
          mountPath: /workspace/jobs/certs

# ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "eirini"
data:
  opi.yaml: |
    opi:
      kube_config: ""
      kube_namespace: {{ .Values.opi.kubernetes_api_endpoint }}
      kube_endpoint: {{ .Values.opi.kubernetes_api_endpoint }}
      nats_password: {{ .Values.secrets.NATS_PASSWORD }}
      nats_ip: "nats.scf.svc.cluster.local"
      api_endpoint: "http://api.{{ .Release.Namespace }}.svc.cluster.local:9022"
      cf_username: "admin"
      cf_password: {{ .Values.secrets.CLUSTER_ADMIN_PASSWORD }}
      external_eirini_address: {{ if .Values.opi.enable_ingress }}"we-love-pandas.{{ .Values.opi.kubernetes_api_endpoint }}:443"{{ else }}"{{ index .Values.kube.external_ips 0 }}:5800"{{ end }}
      skip_ssl_validation: true
      insecure_skip_verify: true

# Service
---
apiVersion: v1
kind: Service
metadata:
  name: "eirini"
spec:
{{- if not .Values.opi.enable_ingress }}
  externalIPs: {{ .Values.kube.external_ips | toJson }}
{{- end }}
  ports:
    - port: 8085
      protocol: TCP
      name: opi
    - port: {{ if .Values.opi.enable_ingress }}8080{{ else }}5800{{ end }}
      protocol: TCP
      targetPort: 8080
      name: registry
  selector:
    name: "eirini"

{{- if .Values.opi.enable_ingress }}
# Ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eirini-registry
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  tls:
    - hosts:
      - "we-love-pandas.{{ .Values.opi.kubernetes_api_endpoint }}:443"
      secretName: private-registry-cert
  rules:
    - host: "we-love-pandas.{{ .Values.opi.kubernetes_api_endpoint }}:443"
      http:
        paths:
          - path: /
            backend:
              serviceName: eirini
              servicePort: 8080
{{- end }}

# Service Account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opi
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: opi-clust-admin-binding
subjects:
  - kind: ServiceAccount
    name: opi
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

# create-certs
---
kind: Job
apiVersion: batch/v1
metadata:
  name: create-certs
spec:
  template:
    metadata:
      name: create-certs
    spec:
      serviceAccountName: "opi"
      restartPolicy: OnFailure
      containers:
      - name: create-certs
        env:
        - name: REGISTRY
          value: {{ if .Values.opi.enable_ingress }}"we-love-pandas.{{ .Values.opi.kubernetes_api_endpoint }}"{{ else }}"{{ index .Values.kube.external_ips 0 }}"{{ end }}
        image: eirini/certs-generate
        imagePullPolicy: Always

# copy-certs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-copier
spec:
  template:
    spec:
      serviceAccountName: "opi"
      restartPolicy: OnFailure
      volumes:
      - name: host-docker
        hostPath:
          path: /etc/docker
          type: Directory
      containers:
      - name: copy-certs
        env:
        - name: REGISTRY
          value: {{ if .Values.opi.enable_ingress }}"we-love-pandas.{{ .Values.opi.kubernetes_api_endpoint }}:443"{{ else }}"{{ index .Values.kube.external_ips 0 }}:5800"{{ end }}
        image: eirini/certs-copy
        volumeMounts:
        - name: host-docker
          mountPath: /workspace/docker
