---
{{- if eq (printf "%s" .Values.kube.auth) "rbac" }}
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "RoleBinding"
metadata:
  name: "default-configgin-role-binding"
subjects:
- kind: "ServiceAccount"
  name: "default"
roleRef:
  kind: "Role"
  name: "configgin-role"
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}
---
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") .Values.kube.psp.nonprivileged }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "default-binding-psp"
subjects:
- kind: "ServiceAccount"
  name: "default"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: "ClusterRole"
  name: "psp-role-nonprivileged"
  apiGroup: "rbac.authorization.k8s.io"
{{- end }}
