---
{{- if and (eq (printf "%s" .Values.kube.auth) "rbac") .Values.kube.psp.privileged }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "psp-role-privileged"
rules:
- apiGroups:
  - "extensions"
  resourceNames:
  - {{ .Values.kube.psp.privileged | quote }}
  resources:
  - "podsecuritypolicies"
  verbs:
  - "use"
{{- end }}
